# Generated by Django 3.0.8 on 2020-07-13 11:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This is your default Bio, go to Settings ⚙️ to change', max_length=500, verbose_name=django.contrib.auth.models.User),
        ),
    ]
