# Generated by Django 3.0.8 on 2020-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userextra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtra',
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registrationnumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
